### ISSUE TITLE
Solution is not defined

### ISSUE THREAD

**Issue by YangWang77** [chenpengcheng/cli#6]
When I typed "Check" or "Run", it shows Line 10: NameError: global name 'Solution' is not defined. :)
Also, do i need to control + d every time I want to use "vim" command to type the code? It does not work when I was running ./cli.py.

**Comment by blockchainian** [comment]
@YangWang77 Thanks for the feedback!

Have you tried `tmux`? Running `./cli.py` and `vim` in separate panes would allow you edit and test at the same time.

`Line 10: NameError: global name 'Solution' is not defined` means that you did not define a `Solution` class in your Python code. Please take a look at the example solution: https://github.com/chenpengcheng/leetcode/blob/master/1.py
