### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by nuynait** [chenpengcheng/cli#8]
When install `sudo easy_install leetcode-cli` I get an error:

```
error: [Errno 2] No such file or directory: 'README.md'
```

**Comment by blockchainian** [comment]
@nuynait Can you try to install it through PIP? `sudo pip install leetcode-cli`. It works for me.

**Comment by nuynait** [comment]
Emm... very strange. I tried your suggestion through PIP, it gives me following error:

```
Found existing installation: six 1.4.1
Cannot uninstall 'six'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

Then I tried running `sudo easy_install leetcode-cli`, it no longer have the previous error anymore, but a new error appears:

```
pkg_resources.DistributionNotFound: The 'soupsieve>=1.2' distribution was not found and is required by beautifulsoup4
```

Then I tried install through PIP again and this time install succeed.

Feels like when install dependencies, some can install using `easy_install`, some able to install using `pip install`.

**Comment by blockchainian** [comment]
@nuynait Cool! I never figured out all these dependency things!
